#!/bin/sh

[ "$(dirname "$0")" != "docker" ] && echo "please use the command with the docker/<CMD> folder" && exit 1

sudo chown -R $(whoami):$(whoami) ./app

sudo docker exec -it node-devserver sh -c "echo \"Node version: $(node -v)\" && nodemon ${@}"
