#!/bin/sh

[ "$(dirname "$0")" != "docker" ] && echo "please use the command with the docker/<CMD> folder" && exit 1

sudo chown -R $(whoami):$(whoami) ./app

sudo docker compose -p node_dev_server -f docker/compose.yml stop
sudo docker compose -p node_dev_server -f docker/compose.yml rm -f
