#!/bin/sh

[ "$(dirname "$0")" != "docker" ] && echo "please use the command with the docker/<CMD> folder" && exit 1

sudo chown -R $(whoami):$(whoami) ./app

VERSION=${1:-20}

sed -i "s/^NODE_VERSION=.*/NODE_VERSION=$VERSION/" docker/.env
